# Generated by Django 2.2 on 2019-05-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='thumb',
            field=models.ImageField(editable=False, null=True, upload_to='uploads/'),
        ),
    ]
